name: flutter_wlk_customer
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


  dio: ^5.1.1
  flutter_easyloading: ^3.0.0
  sticky_headers: ^0.3.0+2 #日历需要
  get: ^4.6.5
  flutter_screenutil: ^5.9.0
  flustars_flutter3: ^3.0.0 #工具类 SpUtil，ScreenUtil, DirectoryUtil等等。
  pull_to_refresh: ^2.0.0
  permission_handler: ^12.0.1
  flutter_staggered_grid_view: ^0.7.0 #瀑布流
  image_picker: ^1.1.0 #相册单选
#  images_picker: ^1.2.11 #相册多选
  image_gallery_saver_plus: ^4.0.1 #保存到相册
  photo_view: ^0.15.0 #查看大图
  flutter_widget_from_html_core: ^0.16.0 #html
  transparent_image: ^2.0.1 #图片懒加载
#  flutter_cached_pdfview: ^0.4.3 #pdf文件
#  webview_flutter: ^4.8.0
  video_player: ^2.6.1 #视频
#  perfect_volume_control: ^1.0.5 #声音
  screen_brightness: ^2.0.1 #亮度
  provider: ^6.0.3
#  wakelock: ^0.6.2
  wakelock_plus: ^1.2.5
  url_launcher: ^6.1.10


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
